version: '3.9'
services:
  zookeeper-server:
    image: "bitnami/zookeeper:latest"
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: "bitnami/kafka:latest"
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-server:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper-server

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-server:29092"
    depends_on:
      - "kafka-server"

  mysql:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssw0rd
      - MARIADB_DATABASE=micro
      - MARIADB_USER=bond
      - MARIADB_PASSWORD=P@ssw0rd
    ports:
      - 3306:3306
